### ISSUE TITLE
Not work with the Status: Ticket Import Failed

### ISSUE THREAD

**Issue by JB1985** [xxxmicrobexxx/whmcsEmailImportHook#1]
Hello, 

this hook see only the blocked Tickets with the Status "Blocked Potential Email Loop" but not the important one "Ticket Import Failed".

**Comment by VJPandaAU** [comment]
Here is what I see - it shows exactly what it is meant to, blocked support tickets.

![screenshot](https://user-images.githubusercontent.com/1052491/133206401-6942e0b4-4866-47a7-9fa5-7c67db5a2d2b.png)

**Comment by JB1985** [comment]
Which WHMCS Version do you use?

**Comment by VJPandaAU** [comment]
I have updated the code so that now it displays all unsuccessful tickets instead of just blocked.

**Comment by VJPandaAU** [comment]
Sorry, I didn't see your response.  WHMCS 8.2.1
