### ISSUE TITLE
Not working since upgrading to 8.3

### ISSUE THREAD

**Issue by solaceten** [xxxmicrobexxx/whmcsEmailImportHook#2]
just shows recent activity - not blocked emails....

**Comment by solaceten** [comment]
Here is what I am using


`<?php
// https://whmcs.community/topic/296515-hook-to-show-recent-imported-ticket-failures-on-support-tickets-page/
// version 1.4

use Illuminate\Database\Capsule\Manager as Capsule; 

add_hook('AdminSupportTicketPagePreTickets', 1, function($vars) {
	
	$output = "<div id='recently-blocked'><h2>Recently Blocked Messages   <small><i class='far fa-eye'></i> <a href='systemmailimportlog.php' target='_blank'>SEE ALL</a></small></h2>
		<table id='sortabletbl1' class='datatable' style='width:100%'>
		<tr><th>Date</th><th>Name/Email</th><th>Subject (click to view)</th><th>Status</th></tr>";
	
                 //foreach (Capsule::table('tblticketmaillog')->where('status', 'not like', '%Successfully%')->where('email', 'not like', 'mailer-daemon%')->orderBy('id', 'desc')->limit(10)->get() as $msg){
		
		foreach (Capsule::table('tblticketmaillog')->where('status', 'not like', '%Successfully%')->where('status', 'not like', '%Blocked sender%')->where('status', 'not like', '%Prevented an Auto Responder%')->where('email', 'not like', 'mailer-daemon%')->orderBy('id', 'desc')->limit(10)->get() as $msg){


		/* Name */
		if ($msg->name === $msg->email) $name = $msg->name;
		else $name = "{$msg->name} <{$msg->email}>";
		
		/* Date */
		$today = new DateTime();
		$msg_date = new DateTime($msg->date);
		$interval = $today->diff($msg_date);
		$date_interval = abs($interval->format('%R%a'));
		
		if ($date_interval == 0 && $interval->h < date('H')) {
		    $date_interval = 'Today';
		}
		else if ($date_interval == 0 && $interval->h >= date('H')){
		    $date_interval = 'Yesterday';
		}
		else if ($date_interval == 1) $date_interval = 'Yesterday';
		else $date_interval .= ' days ago';

		$output .= "
		<tr>
			<td>$date_interval</td><td>$name</td><td><a href='#' onclick=\"window.open('/" . $GLOBALS['customadminpath'] . "/systemmailimportlog.php?display=true&id={$msg->id}','','width=650,height=400,scrollbars=yes');return false\">{$msg->subject}</a></td><td>{$msg->status}</td></tr>";
		
	}
	
	return  "$output</table><br /></div>
	<script>
        jQuery(document).ready(function($){ /* Move to bottom of page */
        $('#recently-blocked').appendTo('#contentarea > div:first-child');
        });
    </script>";
	
});

`

**Comment by VJPandaAU** [comment]
WHMCS 8.3 is not in general release.

When it is, if there are any problems I will update the hook.  If you can see what isn't working and can do a pull request that would be appreciated.

**Comment by solaceten** [comment]
> WHMCS 8.3 is not in general release.
> When it is, if there are any problems I will update the hook. If you can see what isn't working and can do a pull request that would be appreciated.

Hi - I installed the update to 8.3.0 when I was prompted that an update was available inside WHMCS.  Also, their blog Oct 13th says it's general release:  https://blog.whmcs.com/133703/whmcs-83-promoted-to-general-availability

As to what's not working: basically, it no longer lists the failed imports.

**Comment by VJPandaAU** [comment]
I have just updated it.  There is a minor change in their code that caused the hook to display all ticket emails.  I suspect that you were seeing successful imports and failed were over the fold.  Let me know how you go with the update.

**Comment by solaceten** [comment]
Yes it's working great again now :-0
